---
title: Czy dostał kredyt?
---

graph TD
    A[Dochody] --> B[Niskie]
    A --> C[Średnie]
    A --> D[Wysokie]
    B --> E[Wkład Własny]
    E --> F[">20%"]
    E --> G["10%"]
    F --> H[Tak]
    G --> I[Nie]
    C --> J[Stan Cywilny]
    J --> K[W Związku]
    J --> L[Wolny]
    K --> M[Tak]
    L --> N[Nie]
    D --> O[Tak]
